models/Events.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "events".
 *
 * @property integer $id
 * @property integer $calendar_id
 * @property string $time
 * @property string $content
 * @property string $comment
 *
 * @property Calendar $calendar
 */
class Events extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'events';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['calendar_id', 'time'], 'required'],
            [['calendar_id'], 'integer'],
            [['time'], 'safe'],
            [['content', 'comment'], 'string'],
            [['calendar_id'], 'exist', 'skipOnError' => true, 'targetClass' => Calendar::className(), 'targetAttribute' => ['calendar_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'calendar_id' => 'Calendar ID',
            'time' => 'Время',
            'content' => 'Содержание записи',
            'comment' => 'Комментарий',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCalendar()
    {
        return $this->hasOne(Calendar::className(), ['id' => 'calendar_id']);
    }
}

controllers/EventsController.php
<?php

namespace app\controllers;

use app\models\Calendar;
use app\models\Notifications;
use app\models\User;
use Faker\Provider\DateTime;
use Yii;
use app\models\Events;
use app\models\EventsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EventsController implements the CRUD actions for Events model.
 */
class EventsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => \app\filters\BannedFilter::className(),
            ],
			'access' => [
				'class' => \yii\filters\AccessControl::className(),
				'rules' => [
				   [
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Events models.
     * @return mixed
     */
    public function actionIndex($date = null)
    {
        if($date == null)
        {
            $calendar = Calendar::findByCurrentDate();
        } else {
            $calendar = Calendar::find()->where(['date' => $date])->one();
        }

        if($calendar == null)
        {
            $this->updateCalendar(date('Y', strtotime($date)));
            $calendar = Calendar::findByCurrentDate();
        }

        $searchModel = new EventsSearch();
        $dataProvider = $searchModel->searchByCalendar(Yii::$app->request->queryParams, $calendar->id);


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'calendarId' => $calendar->id,
        ]);
    }

    /**
     * Displays a single Events model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Events model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($calendarId, $calendarDate = null)
    {
        $model = new Events();
        $model->calendar_id = $calendarId;

        if($calendarDate == null)
            $calendarDate = date('Y-m-d');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'date' => $calendarDate]);
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Events model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $calendarDate = null)
    {
        $model = $this->findModel($id);

        if($calendarDate == null)
            $calendarDate = date('Y-m-d');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'date' => $calendarDate]);
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Events model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->delete();
        $calendar = Calendar::find()->where(['id' => $model->calendar_id])->one();

        return $this->redirect(['index', 'date' => $calendar->date]);
    }

    /**
     * Оповещает всех пользователей о событии
     * @param $id
     * @return mixed
     */
    public function actionNotify($id)
    {
        $event = $this->findModel($id);
        $calendar = $event->calendar;
        $userId = Yii::$app->user->identity->id;
        $result = Notifications::globalNotify($userId, 'Оповещение', "
            $event->content<br><i>Дата: $calendar->date $event->time</i>
        ");

        return $this->renderAjax('_sender-message', [
            'result' => $result,
        ]);
    }

    /**
     * Finds the Events model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Events the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Events::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	 public function print_arr($array) {
        echo '<pre>'.print_r($array, true).'</pre>';
    }

    /**
     * Записывает в календарь все даты на год
     * @param $year
     * @return mixed
     */
    public function updateCalendar($year = null)
    {
        if($year == null)
        {
            $year = date('Y');
        }

        $fromDate = new \DateTime(date('Y-m-d', strtotime(date($year.'-01-01'))));
        $toDate = new \DateTime(date('Y-m-t' , strtotime(date($year.'-12-t'))));

        $period = new \DatePeriod($fromDate, new \DateInterval('P1D'), $toDate);

        $arrayOfDates = array_map(
            function($item){return $item->format('Y-m-d');},
            iterator_to_array($period)
        );

        foreach ($arrayOfDates as $date)
        {
            $calendar = new Calendar($date);
            $calendar->save();
        }
    }
}

views/events/_form.php
<?php

use kartik\time\TimePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Events */
/* @var $form yii\widgets\ActiveForm */
?>


			<?php $form = ActiveForm::begin(); ?>

   		<div class="row">
			<div class="col-md-12 vcenter">
				    <?= $form->field($model, 'time')->widget(TimePicker::className(), [
                        'name' => 't1',
                        'pluginOptions' => [
                            'showSeconds' => false,
                            'showMeridian' => false,
                            'minuteStep' => 1,
                            'secondStep' => 5,
                        ]
                    ]) ?>
			</div>
		</div>
   		<div class="row">
			<div class="col-md-12 vcenter">
				    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>				
			</div>
		</div>
   		<div class="row">
			<div class="col-md-12 vcenter">
				    <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>				
			</div>
		</div>
   	
<div style="display:none">
</div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

views/events/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EventsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="events-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'calendar_id') ?>

    <?= $form->field($model, 'datetime') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'comment') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/events/_sender-message.php
<?php
/**
 * Created by PhpStorm.
 * User: Qist
 * Date: 15.04.2017
 * Time: 12:23
 */

?>

<?php if($result) {?>
    <div class="alert alert-success alert-dismissible" style="width: 75%;">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-check"></i> Успех!</h4>
        Все пользователи были успешно оповещены о событии
    </div>
<?php } else { ?>
    <div class="alert alert-danger alert-dismissible" style="width: 75%;">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i> Ошибка!</h4>
        Во время отправки, какому-то из пользователей произошла критическая ошибка. Свяжитесь с разработчиками CRM!
    </div>
<?php } ?>

views/events/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Events */

$this->title = 'Добавить ';
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="events-create">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/events/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EventsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$dateParam = Yii::$app->request->get('date');

if($dateParam)
{
    $date = new \DateTime($dateParam);
} else {
    $date = new \DateTime();
}

$yesterday = $date->sub(new \DateInterval('P1D'))->format('d.m.Y');
$today = $date->add(new \DateInterval('P1D'))->format('d.m.Y');
$tomorrow = $date->add(new \DateInterval('P1D'))->format('d.m.Y');

$this->title = $today;
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="events-index">
	<div class="box box-default">	
		<div class="box-body">
		<!-- <img src="http://cbscao.ru/sites/default/files/pictures/13249/develop900.jpg" alt="Наш логотип">-->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <?php Pjax::begin() ?>
    <p>
        <?= Html::button('Добавить', ['value' => Url::toRoute(['events/create', 'calendarId' => $calendarId, 'calendarDate' => $today]), 'class' => 'btn btn-success', 'id' => 'button-modal_create', 'onClick' => "
           $('#modal-create').modal('show')
            .find('#modal-create_content')
            .load($(this).attr('value'));
        "]) ?>
   </p>

		</div>
	</div>
	</div>

    <?php
        Modal::begin([
            'header' => '<h4>Добавить/изменить запись</h4>',
            'id' => 'modal-create',
            'size' => 'modal-lg'
        ]);

        echo "<div id=\"modal-create_content\"></div>";

        Modal::end();
    ?>

	<div class="box box-default">
		<div class="box-body" style="overflow-x: auto;">
            <div class="btn-group">
                <a href="<?=Url::toRoute(['events/index', 'date' => $yesterday])?>" type="button" class="btn btn-default btn-md" title="<?=$yesterday?>"><i class="fa fa-chevron-left"></i></a>
                <a href="<?=Url::toRoute(['events/index', 'date' => $tomorrow])?>" type="button" class="btn btn-default btn-md" title="<?=$tomorrow?>"><i class="fa fa-chevron-right"></i></a>
            </div>
            <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
			[
			'attribute'=>'time',
			'content'=>function ($data) use ($today){
				return Html::button($data->time.'   ', ['value' => Url::toRoute(['events/update', 'id' => $data->id, 'calendarDate' => $today]), 'class' => 'button-modal_update btn btn-warning btn-xs', 'style'=>'color:#ffffff; font-size: 13px', 'onClick' => "
				   $('#modal-create').modal('show')
                        .find('#modal-create_content')
                        .load($(this).attr('value'));
				"]).'<a href="'.Url::toRoute(['events/notify', 'id' => $data->id]).'" class="btn btn-info btn-xs btn-calendar-notify" title="оповестить всех о событии"><i class="fa fa-bell"></i></a>';
						 
			 },
                'contentOptions' => ['style' => 'width: 100px'],
			],

            // 'id',
            'content:ntext',
            'comment:ntext',
			['class' => 'yii\grid\ActionColumn',
			'template' => '{delete} ',
            'contentOptions' => ['style' => 'width: 10px']],
           // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
	</div>
        <?php Pjax::end() ?>
</div>
</div>

views/events/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Events */

$this->title = 'Изменить ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="events-update">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/events/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Events */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="events-view">


    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены что хотите удалить?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'calendar_id',
            'datetime',
            'content:ntext',
            'comment:ntext',
        ],
    ]) ?>

</div>