models/Tasks.php
<?php

namespace app\models;

use Carbon\Carbon;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "tasks".
 *
 * @property integer $id
 * @property integer $is_late
 * @property string $date_created
 * @property string $name
 * @property integer $performer_id
 * @property string $comment
 * @property integer $exec_time
 * @property string $date_close
 * @property integer $owner_id
 * @property string $status
 *
 * @property User $performer
 */
class Tasks extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tasks';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_created', 'date_close', 'is_late'], 'safe'],
            [['name', 'performer_id', 'comment', 'exec_time'], 'required'],
            [['name', 'comment', 'status'], 'string'],
            [['performer_id', 'exec_time', 'owner_id'], 'integer'],
            [['performer_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['performer_id' => 'id']],
        ];
    }

    public function afterFind()
    {
        $this->date_created = date('Y-m-d', strtotime($this->date_created));
        if($this->date_close != null)
        {
            $this->date_close = date('Y-m-d', strtotime($this->date_close));
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if($this->owner_id == null)
        {
            $this->owner_id = Yii::$app->user->identity->id;
        }

        if($this->isNewRecord)
        {
            $ntf = new Notifications($this->owner_id, $this->performer_id, $this->name, $this->comment);
            $ntf->save();
        } elseif($this->isAttributeChanged('performer_id'))
        {
            $ntf = new Notifications($this->owner_id, $this->performer_id, $this->name, $this->comment);
            $ntf->save();
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date_created' => 'Дата создания задачи',
            'name' => 'Наименование задачи',
            'performer_id' => 'Исполнитель',
            'comment' => 'Комментарий',
            'exec_time' => 'Срок на исполнение (в днях)',
            'date_close' => 'Дата закрытия',
            'owner_id' => 'Автор задачи',
            'status' => 'Статус',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerformer()
    {
        return $this->hasOne(User::className(), ['id' => 'performer_id']);
    }

    /**
     * Возваращает список пользователей
     * @return array
     */
    public function getPerformersList()
    {
        return ArrayHelper::map(User::find()->all(), 'id', function($model, $defaultValue) {
            return $model['last_name']." ".$model['first_name'];
        });
    }

    /**
     * Проверяет задачу на просрочку
     * @return bool
     */
    public function isLating()
    {
        $now = Carbon::now();
        $date_created = Carbon::createFromFormat('Y-m-d', $this->date_created);
        $plan_close_date = $date_created->addDays($this->exec_time);

        $diff = $now->diffInDays($plan_close_date, false);

        if($diff < 0)
            return true;
        else
            return false;
    }
}

controllers/TasksController.php
<?php

namespace app\controllers;

use app\models\Notifications;
use Yii;
use app\models\Tasks;
use app\models\TasksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TasksController implements the CRUD actions for Tasks model.
 */
class TasksController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => \app\filters\BannedFilter::className(),
            ],
			'access' => [
				'class' => \yii\filters\AccessControl::className(),
				'rules' => [
				   [
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tasks models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TasksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tasks model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tasks model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tasks();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Tasks model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Tasks model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionClose($id)
    {
        $model = $this->findModel($id);
        $model->date_close = date('Y-m-d');
        $model->save();

        $ntf = new Notifications($model->performer_id, $model->owner_id, 'Задача закрыта', "Задача под наименованием «".$model->name."» была закрыта");
        $ntf->save();


        return $this->redirect(['index']);
    }

    /**
     * Finds the Tasks model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tasks the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tasks::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	 public function print_arr($array) {
        echo '<pre>'.print_r($array, true).'</pre>';
    }
}

views/tasks/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Tasks */
/* @var $form yii\widgets\ActiveForm */
?>

			<?php $form = ActiveForm::begin(); ?>

        <?php if($model->isNewRecord): ?>
            <div class="row">
                <div class="col-md-12 vcenter">
                        <?= $form->field($model, 'name')->textInput() ?>
                </div>
            </div>
        <?php endif; ?>
   		<div class="row">
			<div class="col-md-12 vcenter">
				    <?= $form->field($model, 'performer_id')->dropDownList($model->getPerformersList(), ['prompt' => 'Выберите исполнителя']) ?>
			</div>
		</div>
   		<div class="row">
			<div class="col-md-12 vcenter">
				    <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>				
			</div>
		</div>
   		<div class="row">
			<div class="col-md-12 vcenter">
				    <?= $form->field($model, 'exec_time')->textInput(['type' => 'number']) ?>
			</div>
		</div>
   	
<div style="display:none">
</div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?php if($model->isNewRecord == false && $model->date_close == null): ?>
            <a href="<?=Url::toRoute(['tasks/close', 'id' => $model->id])?>" class="btn btn-danger">Закрыть</a>
        <?php endif; ?>
    </div>

    <?php ActiveForm::end(); ?>

views/tasks/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TasksSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tasks-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'date_created') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'performer_id') ?>

    <?= $form->field($model, 'comment') ?>

    <?php // echo $form->field($model, 'exec_time') ?>

    <?php // echo $form->field($model, 'date_close') ?>

    <?php // echo $form->field($model, 'owner_id') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/tasks/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Tasks */

$this->title = 'Добавить ';
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tasks-create">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/tasks/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\bootstrap\Modal;

use Carbon\Carbon;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TasksSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Задачи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tasks-index">
	<div class="box box-default">	
		<div class="box-body">
		<!-- <img src="http://cbscao.ru/sites/default/files/pictures/13249/develop900.jpg" alt="Наш логотип">-->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::button('Добавить', ['value' => Url::toRoute(['tasks/create']), 'class' => 'btn btn-success', 'id' => 'button-modal_create', 'onClick' => "
           $('#modal-create')
            .find('#modal-create_content')
            .load($(this).attr('value'));
            $('#modal-create').modal('show');
        "]) ?>
   </p>




            <?php
            Modal::begin([
                'header' => '<h4>Добавить/изменить задачу</h4>',
                'id' => 'modal-create',
                'size' => 'modal-lg'
            ]);

            echo "<div id=\"modal-create_content\"></div>";

            Modal::end();
            ?>

		</div>
	</div>
	</div>
	
	<div class="box box-default">
		<div class="box-body" style="overflow-x: auto;">
	<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions' => function($model){
	        if($model->date_close != null)
	            return ['style' => 'background: #e4e4e4'];

            $now = Carbon::now();
            $date_created = Carbon::createFromFormat('Y-m-d', $model->date_created);
            $plan_close_date = $date_created->addDays($model->exec_time);
//            Carbon::createFromFormat('d-m-Y', $data->date_created)
            $diff = $now->diffInDays($plan_close_date, false);

            if($diff < 0)
                return ['class' => 'danger'];
//				return['style' => 'background: deeppink; color: white'];

	        return ['class' => 'default'];
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
			[
			'attribute'=>'date_created',

			'content'=>function ($data){
                return Html::button(date('d.m.Y', strtotime($data->date_created)).'   ', ['value' => Url::toRoute(['tasks/update', 'id' => $data->id]), 'class' => 'button-modal_update btn btn-warning btn-xs', 'style'=>'color:#ffffff; font-size: 13px', 'onClick' => "
				   $('#modal-create').modal('show')
                        .find('#modal-create_content')
                        .load($(this).attr('value'));
				"]);

			 },
                'contentOptions' => ['style' => 'width: 10px'],
			],

            // 'id',
            'name:ntext',
            [
                'attribute' => 'performer.name',
                'filter' => $searchModel->getPerformersList(),
                'header' => 'Исполнитель',
                'content' => function($data){
	                return $data->performer->last_name.' '.$data->performer->first_name;
                },
            ],
            'comment:ntext',
             'exec_time',
             'date_close:date',
            // 'owner_id',
			['class' => 'yii\grid\ActionColumn',
			'template' => '{delete} '],
           // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
	</div>
</div>
</div>

views/tasks/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tasks */

$this->title = 'Изменить ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="tasks-update">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/tasks/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Tasks */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tasks-view">


    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены что хотите удалить?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'date_created',
            'name:ntext',
            'performer_id',
            'comment:ntext',
            'exec_time:datetime',
            'date_close',
            'owner_id',
            'status:ntext',
        ],
    ]) ?>

</div>